id: P14DC7DE4
initial_creation_type: input
source_metadata:
  title: Tsarchen Losal Gyatso
  language: bo
  description: 'Texts by and about Tsarchen Losal Gyatso (tshar chen blo gsal rgya
    mtsho, 1502-1567), an important master of the Sakya tradition:'
  volume:
    f2eca852ff804a0ba4e402e4d444b9ad:
      title: Prayer to Tsarchen Losal Gyatso
      parent: Prayers
    eae601f47a464ca285b2465da30f5b1e:
      title: 'The Revelling Ocean of Blessings: A Prayer to Tsarchen Dorje Chang'
      parent: Prayers
    6eb18b944c1d4a6c91488b64f3880893:
      title: An Aspirational Prayer to Behold the Beautiful Face of Khecharī
      parent: Vajrayoginī
created_at: '2022-03-01T01:54:45.361147'
last_modified_at: '2022-03-01T01:54:45.361150'
